---
- hosts: websrv

  vars_files:
    - vars/nginx.yml
  sudo: true

  roles:
    - { role: geerlingguy.nginx }
    - php71

- hosts: elasticsrv
  sudo: true
  roles:
    - { role: elastic.elasticsearch, es_instance_name: "node1" }
